name: Build and update Cachix

on:
  push:
    branches: main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: cachix-main
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        host:
          - default
          # Add more hosts:
          # - host-name

    env:
      CACHIX_CACHE: thoren

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Load flake cache config
        run: |
          {
            echo "NIX_CONFIG<<EOF"
            cat ./modules/core/caches.conf
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Set up Cachix
        uses: cachix/cachix-action@v17
        with:
          name: ${{ env.CACHIX_CACHE }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: true

      - name: Build host
        run: |
          nix build \
            ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel" \
            --print-build-logs \
            --out-link result